// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Colors;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Elements;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Minifigs;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Part_categories;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Parts;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Themes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\lego
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LegoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The colors property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Colors.ColorsRequestBuilder Colors
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Colors.ColorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The elements property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Elements.ElementsRequestBuilder Elements
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Elements.ElementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The minifigs property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Minifigs.MinifigsRequestBuilder Minifigs
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Minifigs.MinifigsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The part_categories property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Part_categories.Part_categoriesRequestBuilder Part_categories
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Part_categories.Part_categoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parts property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Parts.PartsRequestBuilder Parts
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Parts.PartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sets property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.SetsRequestBuilder Sets
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.SetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The themes property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Themes.ThemesRequestBuilder Themes
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Themes.ThemesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.LegoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/lego", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.LegoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/lego", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
