// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Swagger;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lego property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.LegoRequestBuilder Lego
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.LegoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The swagger property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Swagger.SwaggerRequestBuilder Swagger
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Swagger.SwaggerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
