// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Badges;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users._token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The _token property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users._token._tokenRequestBuilder _token
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users._token._tokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The badges property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Badges.BadgesRequestBuilder Badges
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Badges.BadgesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Rebrickable.OpenApiClient.api.v3.users.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.WithUser_tokenItemRequestBuilder"/></returns>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.WithUser_tokenItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("user_token", position);
                return new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.WithUser_tokenItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
