// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Allparts;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Build;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Lost_parts;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Minifigs;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Parts;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Profile;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Setlists;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Sets;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\users\{user_token}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUser_tokenItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allparts property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Allparts.AllpartsRequestBuilder Allparts
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Allparts.AllpartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The build property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Build.BuildRequestBuilder Build
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Build.BuildRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lost_parts property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Lost_parts.Lost_partsRequestBuilder Lost_parts
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Lost_parts.Lost_partsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The minifigs property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Minifigs.MinifigsRequestBuilder Minifigs
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Minifigs.MinifigsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partlists property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.PartlistsRequestBuilder Partlists
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.PartlistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parts property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Parts.PartsRequestBuilder Parts
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Parts.PartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Profile.ProfileRequestBuilder Profile
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setlists property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Setlists.SetlistsRequestBuilder Setlists
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Setlists.SetlistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sets property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Sets.SetsRequestBuilder Sets
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Sets.SetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.WithUser_tokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_tokenItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users/{user_token}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.WithUser_tokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_tokenItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users/{user_token}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
