// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\users\{userToken}\partlists\{listId}\parts\{partNum}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPartNumItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Rebrickable.OpenApiClient.api.v3.users.item.partlists.item.parts.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.Item.WithColorItemRequestBuilder"/></returns>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.Item.WithColorItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("colorId", position);
                return new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.Item.WithColorItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.WithPartNumItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPartNumItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users/{userToken}/partlists/{listId}/parts/{partNum}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Users.Item.Partlists.Item.Parts.Item.WithPartNumItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPartNumItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/users/{userToken}/partlists/{listId}/parts/{partNum}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
