// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Alternates;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Minifigs;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Parts;
using Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Sets;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\lego\sets\{set_num}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSet_numItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The alternates property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Alternates.AlternatesRequestBuilder Alternates
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Alternates.AlternatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The minifigs property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Minifigs.MinifigsRequestBuilder Minifigs
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Minifigs.MinifigsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parts property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Parts.PartsRequestBuilder Parts
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Parts.PartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sets property</summary>
        public global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Sets.SetsRequestBuilder Sets
        {
            get => new global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.Sets.SetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.WithSet_numItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSet_numItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/lego/sets/{set_num}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Rebrickable.OpenApiClient.Api.V3.Lego.Sets.Item.WithSet_numItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSet_numItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/lego/sets/{set_num}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
